version: '3'
networks:
    app-tier:
      driver: bridge
services:
    app:
        build: .
        networks:
            - app-tier
    mongodb:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: rootpassword
        ports:
            - 27017:27017
        volumes:
            - mongodb_data_container:/data/db
        networks:
            - app-tier
        
volumes:
    mongodb_data_container: